const { withDangerousMod, withXcodeProject } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const ICON_SETS_DIR = "assets/app-icons/animals";
const BUILD_SETTING = "ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES";

// The alternate icon names, e.g. "Bat" for Bat.appiconset. The sets are
// generated by scripts/generate-app-icons.mjs.
function iconNames(projectRoot) {
  return fs
    .readdirSync(path.join(projectRoot, ICON_SETS_DIR))
    .filter((entry) => entry.endsWith(".appiconset"))
    .map((entry) => entry.replace(/\.appiconset$/, ""))
    .sort();
}

// Registers every animal icon set as an iOS alternate app icon: the sets are
// copied into the asset catalog and listed for actool, which compiles them and
// emits the CFBundleAlternateIcons entries. The icon name iOS expects from
// setAlternateIconName is the animal name.
module.exports = function withAnimalAppIcons(config) {
  config = withDangerousMod(config, [
    "ios",
    (config) => {
      const { projectRoot, platformProjectRoot, projectName } =
        config.modRequest;
      const catalog = path.join(
        platformProjectRoot,
        projectName,
        "Images.xcassets"
      );
      for (const name of iconNames(projectRoot)) {
        fs.cpSync(
          path.join(projectRoot, ICON_SETS_DIR, `${name}.appiconset`),
          path.join(catalog, `${name}.appiconset`),
          { recursive: true }
        );
      }
      return config;
    },
  ]);

  config = withXcodeProject(config, (config) => {
    const names = iconNames(config.modRequest.projectRoot);
    config.modResults.updateBuildProperty(
      BUILD_SETTING,
      `"${names.join(" ")}"`
    );
    return config;
  });

  return config;
};
